apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dailyfeed
data:
  MONGODB_USERNAME: ZGFpbHlmZWVkLXNlYXJjaA==
  MONGODB_PASSWORD: aGl0RW50ZXIjIyM=
  MONGODB_CONNECTION_URI: bW9uZ29kYitzcnY6Ly9kYWlseWZlZWQtc2VhcmNoOmhpdEVudGVyIyMjQGFscGhhMzAwLnN6MzB6Y28ubW9uZ29kYi5uZXQvZGFpbHlmZWVkP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPWFscGhhMzAwJmNvbm5lY3RUaW1lb3V0TVM9MzAwMDAmc29ja2V0VGltZW91dE1TPTMwMDAwJnNlcnZlclNlbGVjdGlvblRpbWVvdXRNUz0zMDAwMA==
