apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dailyfeed
data:
  MYSQL_USERNAME: ZGFpbHlmZWVk
  MYSQL_PASSWORD: aGl0RW50ZXIjIyM=
  MYSQL_HOST: ZGFpbHlmZWVkLWRldi5jN211bzB3YTJkcjEuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb20=
  MYSQL_JDBC_URL: amRiYzpteXNxbDovL2RhaWx5ZmVlZC1kZXYuYzdtdW8wd2EyZHIxLmFwLW5vcnRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29tOjMzMDYvZGFpbHlmZWVkP2NoYXJhY3RlckVuY29kaW5nPVVURi04JnNlcnZlclRpbWV6b25lPVVUQyZyZXdyaXRlQmF0Y2hlZFN0YXRlbWVudHM9dHJ1ZQ==
