apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: infra
spec:
  type: ExternalName
  externalName: alpha300.sz30zco.mongodb.net
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
