apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: infra
spec:
  type: ExternalName
  externalName: dailyfeed-dev.c7muo0wa2dr1.ap-northeast-2.rds.amazonaws.com
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  ## rds와 kind 클러스터의 보안 그룹 설정 필요 (dev 환경의 경우 로컬 IP 허용)
