apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: dailyfeed
type: Opaque
stringData:
  KAFKA_PASSWORD: "kafkakafka123!"
  KAFKA_USER: "user1"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
