apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dailyfeed
type: Opaque
stringData:
  MONGODB_CONNECTION_URI: "mongodb://dailyfeed:hitEnter###@host.docker.internal:27017/dailyfeed?directConnection=true"
  MONGODB_USERNAME: "dailyfeed"
  MONGODB_PASSWORD: "hitEnter###"
