apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dailyfeed
type: Opaque
stringData:
  MONGODB_CONNECTION_URI: "mongodb://dailyfeed:hitEnter###@host.docker.internal:27017/dailyfeed?directConnection=true"
  MONGODB_URI: "mongodb://mongo-dailyfeed-1:27017,mongo-dailyfeed-2:27017,mongo-dailyfeed-3:27017/dailyfeed?replicaSet=rs0"
  MONGODB_USERNAME: "dailyfeed"
  MONGODB_PASSWORD: "hitEnter###"
