apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dailyfeed
data:
  MYSQL_HOST: "host.docker.internal"
  MYSQL_PORT: "23306"
  MYSQL_SCHEMA: "dailyfeed"
  MYSQL_JDBC_URL: "jdbc:mysql://host.docker.internal:23306/dailyfeed?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true"
