apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dailyfeed
data:
  MYSQL_HOST: "mysql-dailyfeed"
  MYSQL_PORT: "3306"
  MYSQL_SCHEMA: "dailyfeed"
  MYSQL_JDBC_URL: "jdbc:mysql://mysql-dailyfeed:3306/dailyfeed?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true"
