apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}-svc
  name: {{ .Values.appName }}-svc
  namespace: dailyfeed
spec:
  ports:
  - port: {{ .Values.portNumber }}
    protocol: TCP
    targetPort: {{ .Values.portNumber }}
  selector:
    app: {{ .Values.appName }}-svc
  type: ClusterIP
status:
  loadBalancer: {}
